---
main:
    mode: 'train'
    phase: 1

train:
    mode: 'VA'
    gpu_ids: [0, 1, 2, 3, 4]
    n_epochs: 100
    freeze_feature_extractor: false
    resume: ''
    only_model: false
    loss: ['NTXent']
    setting: 'AVTS'
    save_dir: '/scratch3/users/cssung/LRW/output/AVTS_all_c3dr50_vgg_768_len72e-2'
    save_frequency: 1
    patience: 0
    val_policy: ['loss']
    show_metric: false

test:
    mode: 'VA'
    gpu_ids: [0]
    predict: 'fc'
    resume: '/scratch3/users/cssung/LRW/output/AVTS_all_c3dr50_vgg_768_len72e-2/best.pth'
    save_dir: '/scratch3/users/cssung/LRW/output/AVTS_all_c3dr50_vgg_768_len72e-2'

dataset:
    size: 224
    fps: 25
    duration: 0.72
    sample_rate: 1
    grayscale: false
    shift_type: 'all'
    img_type: 'faces'
    aud_feat: 'mfcc'
    root: '/scratch4/users/cssung/Datasets/LRW/'

dataloader:
    batch_size: 10
    num_workers: 8

model:
    backbone: ['c3dr50', 'vgg', '']
    predict_label: false
    last_dim: 768
    dropout: 0
    use_teacher: false

optimizer:
    lr: 0.0001
    weight_decay: 0.00001
    gamma: 0.9

tensorboard:
    comment: 'AVTS_all_c3dr50_vgg_768_len72e-2_bs2_lr1e-4'
